### ISSUE TITLE
Hotsbot does not work in Group chats.

### ISSUE THREAD

**Issue by Geertvdc** [Bogardo/helium-hotsbot#1]
I'm running some helium hotspots together with a friend of mine. would be awesome if it would work in a group chat so we get notified together about updates.

followed everything here but that didn't help: https://chatimize.com/telegram-bot-group/

it says bot "does not have access to messages"

As i understood on the discord channel this is not supported yet. would be awesome if it would <3

**Comment by Bogardo** [comment]
@Geertvdc You and your friend can both set up the same Helium account address within Hotsbot, from separate Telegram accounts. This way you'll both receive the updates for the same hotspots.

I'll leave this issue open for now and I will look into the possibility of enabling group chat support for the bot but I hope this is a decent alternative for now.

**Comment by Geertvdc** [comment]
I understand but it would be awesome to see these updates in a group chat so you can comment on them within the group. Makes it a bit more interactive compared to just you and the bot

**Comment by Bogardo** [comment]
I've just released a new version of Hotsbot that includes support for Group chats.
@Geertvdc  Please give it a spin and let me know if it works.
