### ISSUE TITLE
Add other currencies

### ISSUE THREAD

**Issue by davidwhicker** [Bogardo/helium-hotsbot#9]
I wondered if it's possible to have currencies other than usd. 

Great work

**Comment by Bogardo** [comment]
@DavidWhicker That should definitely be possible. The upcoming version will allow for more configuration. Including support for multiple currencies should be fairly trivial to implement. I'll add it to the list. Thanks for bringing it up.

**Comment by davidwhicker** [comment]
Appreciate that thank you. Smashing work. 

I haven't experienced the alerts yet due to the api Maintences thing but I'm excited for it. Keep checking the helium app
